name: Java CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Lint
        run: ./gradlew ktlintCheck
      - name: Build with Gradle
        run: ./gradlew build --scan -s jacocoTestReport
      - name: CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: target/site/jacoco/jacoco.xml


